version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '09:00'
      timezone: 'Europe/Berlin'
    commit-message:
      prefix: 'action'
    labels:
      - 'github-actions :robot:'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '09:00'
      timezone: 'Europe/Berlin'
    commit-message:
      prefix: 'npm-prod'
      prefix-development: 'npm-dev'
    labels:
      - 'dependency :robot:'
