#!/bin/sh

[ -n "$CI" ] && exit 0

if [[ $(git status --porcelain -s) != "" ]]; then
  echo "\n😵 Uncommitted changes found 😵"
  echo "Please \`git add\` and \`git commit\` or \`git stash -u\` them before pushing!\n"

  exit 1
fi

command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }

git lfs pre-push "$@"

exit 0
