name: Combine dependabot prs

on:
  schedule:
    # run every 1st of the month at 00:42 UTC
    - cron: '42 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: use app token
        uses: peter-murray/workflow-application-token-action@dc0413987a085fa17d19df9e47d4677cf81ffef3
        id: generate_token
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.PRIVATE_KEY }}

      - name: combine prs
        id: combine-prs
        uses: github/combine-prs@75478ffc3411703ac6176d818d49d3aa5635db2d
        with:
          pr_title: 🤖 Combined @dependabot PRs
          github_token: ${{ steps.generate_token.outputs.token }}
