name: Test and publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        node: ['10', '12']
    name: Test on Node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v1
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
        if: steps.node-cache.outputs.cache-hit != 'true'
      - run: ./node_modules/.bin/lerna run test

  publish:
    needs: [test]
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@master
        with:
          node-version: 10.x
      - uses: actions/setup-node@master
        with:
          registry-url: 'https://npm.pkg.github.com'
      - uses: actions/cache@v1
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm install --ignore-scripts
        if: steps.node-cache.outputs.cache-hit != 'true'
      - run: ./node_modules/.bin/lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push'
