on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12.x', '13.x']
    name: Test on Node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --ignore-scripts --pure-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: ./node_modules/.bin/lerna run test
