name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    concurrency:
      group: test-${{ github.ref }}
      cancel-in-progress: true

    permissions: read-all

    env:
      CI: true

    strategy:
      matrix:
        node-version:
          - 16

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: |
          npm set-script prepare ""
          npm install --ignore-scripts --pure-lockfile

      - run: npm run build --if-present

      - run: npx lerna run test

  test:
    runs-on: ubuntu-latest

    needs: test-matrix

    steps:
      - run: echo "success"
