name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    env:
      CI: true

    permissions: read-all

    strategy:
      matrix:
        node-version:
          - 16

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          lfs: true

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install --ignore-scripts --pure-lockfile

      - run: npm run build --if-present

      - run: npx lerna run test

  test:
    runs-on: ubuntu-latest

    needs: test-matrix

    steps:
      - run: echo "success"
