on:
  pull_request:
  push:
    branches-ignore:
      - main

name: Test

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: set up
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: get cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
        id: npm-cache

      - name: use cache
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-

      - name: dependencies
        run: npm install --ignore-scripts --pure-lockfile

      - name: build
        run: npm run build --if-present
        env:
          CI: true

      - name: test
        run: npx lerna run test
        env:
          CI: true
